v0.0.2

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -5,6 +5,7 @@ APP="teller"
 BUILD_HOST="192.168.59.104"
 BUILD_USER="dave"
 BUILD_AT="/tmp/edeliver/myapp/builds"
+RELEASE_DIR="$BUILD_AT/_build/prod/rel/teller/"
 
 STAGING_HOSTS="192.168.59.103"
 STAGING_USER="dave"
@@ -18,4 +19,28 @@ pre_erlang_get_and_update_deps() {
       ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
     "
   fi
+}
+
+
+pre_erlang_clean_compile() {
+  status "Running phoenix.digest" # log output prepended with "----->"
+  __sync_remote " # runs the commands on the build host
+    # [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+    source ~/.profile
+    # echo \$PATH # check if rbenv is in the path
+    set -e # fail if any command fails (recommended)
+    cd '$BUILD_AT' # enter the build directory on the build host (required)
+    # prepare something
+    mkdir -p priv/static # required by the phoenix.digest task
+    ( cd assets;
+      echo install npm modules
+      npm install >/dev/null;
+      echo brunch up the assets
+      ./node_modules/brunch/bin/brunch build --production
+    )     
+
+    # run your custom task
+    echo and create the digest
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
+  "
 }
